baseUrl = ""
title = "LEP Docs"
languageCode = "en"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON"]
